<?php

use App\Entities\Language\Language;

/**
 * Class LanguagesTableSeeder
 *
 * @author Nick Menke <nick@nlmenke.net>
 */
class LanguagesTableSeeder extends AbstractSeeder
{
    /**
     * Tables that should be truncated before running.
     *
     * @var array
     */
    protected $truncateTables = [
        CreateLanguagesTable::TABLENAME
    ];

    /**
     * Items to be added to the database.
     *
     * @var array
     */
    protected $itemList = [
        ['iso_alpha_2' => 'aa', 'iso_alpha_3' => 'aar', 'name' => 'Afar', 'native' => 'Afaraf'],
        ['iso_alpha_2' => 'ab', 'iso_alpha_3' => 'abk', 'name' => 'Abkhazian', 'native' => 'аҧсуа бызшәа', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ae', 'iso_alpha_3' => 'ave', 'name' => 'Avestan', 'native' => 'avesta'],
        ['iso_alpha_2' => 'af', 'iso_alpha_3' => 'afr', 'name' => 'Afrekaans', 'native' => 'Afrikaans'],
        ['iso_alpha_2' => 'ak', 'iso_alpha_3' => 'aka', 'name' => 'Akan', 'native' => 'Akan'],
        ['iso_alpha_2' => 'am', 'iso_alpha_3' => 'amh', 'name' => 'Amharic', 'native' => 'አማርኛ', 'script' => 'Ethi'],
        ['iso_alpha_2' => 'an', 'iso_alpha_3' => 'arg', 'name' => 'Aragonese', 'native' => 'aragonés'],
        ['iso_alpha_2' => 'ar', 'iso_alpha_3' => 'ara', 'name' => 'Arabic', 'native' => 'العربية‏', 'script' => 'Arab'],
        ['iso_alpha_2' => 'as', 'iso_alpha_3' => 'asm', 'name' => 'Assamese', 'native' => 'অসমীয়া', 'script' => 'Beng'],
        ['iso_alpha_2' => 'av', 'iso_alpha_3' => 'ava', 'name' => 'Avaric', 'native' => 'авар мацӀ', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ay', 'iso_alpha_3' => 'aym', 'name' => 'Aymara', 'native' => 'aymar aru'],
        ['iso_alpha_2' => 'az', 'iso_alpha_3' => 'aze', 'name' => 'Azerbaijani', 'native' => 'azərbaycan dili'],
        ['iso_alpha_2' => 'ba', 'iso_alpha_3' => 'bak', 'name' => 'Bashkir', 'native' => 'башҡорт теле', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'be', 'iso_alpha_3' => 'bel', 'name' => 'Belarusian', 'native' => 'беларуская мова', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'bg', 'iso_alpha_3' => 'bul', 'name' => 'Bulgarian', 'native' => 'български език', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'bh', 'iso_alpha_3' => 'bih', 'name' => 'Bihari', 'native' => 'भोजपुरी', 'script' => 'Deva'],
        ['iso_alpha_2' => 'bi', 'iso_alpha_3' => 'bis', 'name' => 'Bislama', 'native' => 'Bislama'],
        ['iso_alpha_2' => 'bm', 'iso_alpha_3' => 'bam', 'name' => 'Bambara', 'native' => 'bamanankan'],
        ['iso_alpha_2' => 'bn', 'iso_alpha_3' => 'ben', 'name' => 'Bengali', 'native' => 'বাংলা', 'script' => 'Beng'],
        ['iso_alpha_2' => 'bo', 'iso_alpha_3' => 'bod', 'name' => 'Tibetan', 'native' => 'བོད་ཡིག', 'script' => 'Tibt'],
        ['iso_alpha_2' => 'br', 'iso_alpha_3' => 'bre', 'name' => 'Breton', 'native' => 'brezhoneg'],
        ['iso_alpha_2' => 'bs', 'iso_alpha_3' => 'bos', 'name' => 'Bosnian', 'native' => 'bosanski jezik'],
        ['iso_alpha_2' => 'ca', 'iso_alpha_3' => 'cat', 'name' => 'Catalan', 'native' => 'català'],
        ['iso_alpha_2' => 'ce', 'iso_alpha_3' => 'che', 'name' => 'Chechen', 'native' => 'нохчийн мотт', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ch', 'iso_alpha_3' => 'cha', 'name' => 'Chamorro', 'native' => 'Chamoru'],
        ['iso_alpha_2' => 'co', 'iso_alpha_3' => 'cos', 'name' => 'Corsican', 'native' => 'corsu'],
        ['iso_alpha_2' => 'cr', 'iso_alpha_3' => 'cre', 'name' => 'Cree', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'script' => 'Cans'],
        ['iso_alpha_2' => 'cs', 'iso_alpha_3' => 'ces', 'name' => 'Czech', 'native' => 'čeština'],
        ['iso_alpha_2' => 'cu', 'iso_alpha_3' => 'chu', 'name' => 'Church Slavic', 'native' => 'ѩзыкъ словѣньскъ', 'script' => 'Cyrs'],
        ['iso_alpha_2' => 'cv', 'iso_alpha_3' => 'chv', 'name' => 'Chuvash', 'native' => 'чӑваш чӗлхи', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'cy', 'iso_alpha_3' => 'cym', 'name' => 'Welsh', 'native' => 'Cymraeg'],
        ['iso_alpha_2' => 'da', 'iso_alpha_3' => 'dan', 'name' => 'Danish', 'native' => 'dansk'],
        ['iso_alpha_2' => 'de', 'iso_alpha_3' => 'deu', 'name' => 'German', 'native' => 'Deutsch'],
        ['iso_alpha_2' => 'dv', 'iso_alpha_3' => 'div', 'name' => 'Divehi', 'native' => 'ދިވެހި', 'script' => 'Thaa'],
        ['iso_alpha_2' => 'dz', 'iso_alpha_3' => 'dzo', 'name' => 'Dzongkha', 'native' => 'རྫོང་ཁ', 'script' => 'Tibt'],
        ['iso_alpha_2' => 'ee', 'iso_alpha_3' => 'ewe', 'name' => 'Ewe', 'native' => 'Eʋegbe'],
        ['iso_alpha_2' => 'el', 'iso_alpha_3' => 'ell', 'name' => 'Greek', 'native' => 'ελληνικά', 'script' => 'Grek'],
        ['iso_alpha_2' => 'en', 'iso_alpha_3' => 'eng', 'name' => 'English', 'native' => 'English'],
        ['iso_alpha_2' => 'eo', 'iso_alpha_3' => 'epo', 'name' => 'Esperanto', 'native' => 'Esperanto'],
        ['iso_alpha_2' => 'es', 'iso_alpha_3' => 'spa', 'name' => 'Spanish', 'native' => 'Español'],
        ['iso_alpha_2' => 'et', 'iso_alpha_3' => 'est', 'name' => 'Estonian', 'native' => 'eesti'],
        ['iso_alpha_2' => 'eu', 'iso_alpha_3' => 'eus', 'name' => 'Basque', 'native' => 'euskara'],
        ['iso_alpha_2' => 'fa', 'iso_alpha_3' => 'fas', 'name' => 'Persian', 'native' => 'فارسی', 'script' => 'Arab'],
        ['iso_alpha_2' => 'ff', 'iso_alpha_3' => 'ful', 'name' => 'Fulah', 'native' => 'Pulaar'],
        ['iso_alpha_2' => 'fi', 'iso_alpha_3' => 'fin', 'name' => 'Finnish', 'native' => 'suomi'],
        ['iso_alpha_2' => 'fo', 'iso_alpha_3' => 'fao', 'name' => 'Faroese', 'native' => 'føroyskt'],
        ['iso_alpha_2' => 'fr', 'iso_alpha_3' => 'fra', 'name' => 'French', 'native' => 'français'],
        ['iso_alpha_2' => 'fy', 'iso_alpha_3' => 'fry', 'name' => 'Frisian', 'native' => 'Frysk'],
        ['iso_alpha_2' => 'ga', 'iso_alpha_3' => 'gle', 'name' => 'Irish', 'native' => 'Gaeilge'],
        ['iso_alpha_2' => 'gd', 'iso_alpha_3' => 'gla', 'name' => 'Gaelic', 'native' => 'Gàidhlig'],
        ['iso_alpha_2' => 'gl', 'iso_alpha_3' => 'glg', 'name' => 'Galician', 'native' => 'Galego'],
        ['iso_alpha_2' => 'gn', 'iso_alpha_3' => 'grn', 'name' => 'Guaraní', 'native' => 'Avañe\'ẽ'],
        ['iso_alpha_2' => 'gu', 'iso_alpha_3' => 'guj', 'name' => 'Gujarati', 'native' => 'ગુજરાતી', 'script' => 'Gujr'],
        ['iso_alpha_2' => 'gv', 'iso_alpha_3' => 'glv', 'name' => 'Manx', 'native' => 'Gaelg'],
        ['iso_alpha_2' => 'ha', 'iso_alpha_3' => 'hau', 'name' => 'Hausa', 'native' => 'Hausa'],
        ['iso_alpha_2' => 'he', 'iso_alpha_3' => 'heb', 'name' => 'Hebrew', 'native' => 'עברית', 'script' => 'Hebr'],
        ['iso_alpha_2' => 'hi', 'iso_alpha_3' => 'hin', 'name' => 'Hindi', 'native' => 'हिन्दी', 'script' => 'Deva'],
        ['iso_alpha_2' => 'ho', 'iso_alpha_3' => 'hmo', 'name' => 'Hiri Motu', 'native' => 'Hiri Motu'],
        ['iso_alpha_2' => 'hr', 'iso_alpha_3' => 'hrv', 'name' => 'Croatian', 'native' => 'hrvatski jezik'],
        ['iso_alpha_2' => 'ht', 'iso_alpha_3' => 'hat', 'name' => 'Haitian', 'native' => 'Kreyòl ayisyen'],
        ['iso_alpha_2' => 'hu', 'iso_alpha_3' => 'hun', 'name' => 'Hungarian', 'native' => 'magyar'],
        ['iso_alpha_2' => 'hy', 'iso_alpha_3' => 'hye', 'name' => 'Armenian', 'native' => 'Հայերեն', 'script' => 'Armn'],
        ['iso_alpha_2' => 'hz', 'iso_alpha_3' => 'her', 'name' => 'Herero', 'native' => 'Otjiherero'],
        ['iso_alpha_2' => 'ia', 'iso_alpha_3' => 'ina', 'name' => 'Interlingua', 'native' => 'Interlingua'],
        ['iso_alpha_2' => 'id', 'iso_alpha_3' => 'ind', 'name' => 'Indonesian', 'native' => 'Bahasa Indonesia'],
        ['iso_alpha_2' => 'ie', 'iso_alpha_3' => 'ile', 'name' => 'Interlingue', 'native' => 'Interlingue'],
        ['iso_alpha_2' => 'ig', 'iso_alpha_3' => 'ibo', 'name' => 'Igbo', 'native' => 'Asụsụ Igbo'],
        ['iso_alpha_2' => 'ii', 'iso_alpha_3' => 'iii', 'name' => 'Nuosu', 'native' => 'ꆈꌠ꒿', 'script' => 'Yiii'],
        ['iso_alpha_2' => 'ik', 'iso_alpha_3' => 'ipk', 'name' => 'Inupiaq', 'native' => 'Iñupiaq'],
        ['iso_alpha_2' => 'io', 'iso_alpha_3' => 'ido', 'name' => 'Ido', 'native' => 'Ido'],
        ['iso_alpha_2' => 'is', 'iso_alpha_3' => 'isl', 'name' => 'Icelandic', 'native' => 'Íslenska'],
        ['iso_alpha_2' => 'it', 'iso_alpha_3' => 'ita', 'name' => 'Italian', 'native' => 'Italiano'],
        ['iso_alpha_2' => 'iu', 'iso_alpha_3' => 'iku', 'name' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'script' => 'Cans'],
        ['iso_alpha_2' => 'ja', 'iso_alpha_3' => 'jpn', 'name' => 'Japanese', 'native' => '日本語', 'script' => 'Jpan'],
        ['iso_alpha_2' => 'jv', 'iso_alpha_3' => 'jav', 'name' => 'Javanese', 'native' => 'ꦧꦱꦗꦮ', 'script' => 'Java'],
        ['iso_alpha_2' => 'ka', 'iso_alpha_3' => 'kat', 'name' => 'Georgian', 'native' => 'ქართული', 'script' => 'Geor'],
        ['iso_alpha_2' => 'kg', 'iso_alpha_3' => 'kok', 'name' => 'Kongo', 'native' => 'Kikongo'],
        ['iso_alpha_2' => 'ki', 'iso_alpha_3' => 'kik', 'name' => 'Kikuyu', 'native' => 'Gĩkũyũ'],
        ['iso_alpha_2' => 'kj', 'iso_alpha_3' => 'kua', 'name' => 'Kuanyama', 'native' => 'Kuanyama'],
        ['iso_alpha_2' => 'kk', 'iso_alpha_3' => 'kaz', 'name' => 'Kazakh', 'native' => 'қазақ тілі', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'kl', 'iso_alpha_3' => 'kal', 'name' => 'Kalaallisut', 'native' => 'kalaallisut'],
        ['iso_alpha_2' => 'km', 'iso_alpha_3' => 'khm', 'name' => 'Khmer', 'native' => 'ភាសាខ្មែរ', 'script' => 'Khmr'],
        ['iso_alpha_2' => 'kn', 'iso_alpha_3' => 'kan', 'name' => 'Kannada', 'native' => 'ಕನ್ನಡ', 'script' => 'Knda'],
        ['iso_alpha_2' => 'ko', 'iso_alpha_3' => 'kor', 'name' => 'Korean', 'native' => '한국어', 'script' => 'Hang'],
        ['iso_alpha_2' => 'kr', 'iso_alpha_3' => 'kau', 'name' => 'Kanuri', 'native' => 'Kanuri'],
        ['iso_alpha_2' => 'ks', 'iso_alpha_3' => 'kas', 'name' => 'Kashmiri', 'native' => 'कश्मीरी', 'script' => 'Deva'],
        ['iso_alpha_2' => 'ku', 'iso_alpha_3' => 'kur', 'name' => 'Kurdish', 'native' => 'کوردی‎', 'script' => 'Arab'],
        ['iso_alpha_2' => 'kv', 'iso_alpha_3' => 'kom', 'name' => 'Komi', 'native' => '‎коми кыв', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'kw', 'iso_alpha_3' => 'cor', 'name' => 'Cornish', 'native' => 'Kernewek'],
        ['iso_alpha_2' => 'ky', 'iso_alpha_3' => 'kir', 'name' => 'Kyrgyz', 'native' => 'Кыргызча', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'la', 'iso_alpha_3' => 'lat', 'name' => 'Latin', 'native' => 'lingua latina'],
        ['iso_alpha_2' => 'lb', 'iso_alpha_3' => 'ltz', 'name' => 'Luxembourgish', 'native' => 'Lëtzebuergesch'],
        ['iso_alpha_2' => 'lg', 'iso_alpha_3' => 'lug', 'name' => 'Ganda', 'native' => 'Luganda'],
        ['iso_alpha_2' => 'li', 'iso_alpha_3' => 'lim', 'name' => 'Limburgan', 'native' => 'Limburgs'],
        ['iso_alpha_2' => 'ln', 'iso_alpha_3' => 'lin', 'name' => 'Lingala', 'native' => 'Lingála'],
        ['iso_alpha_2' => 'lo', 'iso_alpha_3' => 'lao', 'name' => 'Lao', 'native' => 'ພາສາລາວ', 'script' => 'Laoo'],
        ['iso_alpha_2' => 'lt', 'iso_alpha_3' => 'lit', 'name' => 'Lithuanian', 'native' => 'lietuvių kalba'],
        ['iso_alpha_2' => 'lu', 'iso_alpha_3' => 'lub', 'name' => 'Luba-Katanga', 'native' => 'Kiluba'],
        ['iso_alpha_2' => 'lv', 'iso_alpha_3' => 'lav', 'name' => 'Latvian', 'native' => 'latviešu valoda'],
        ['iso_alpha_2' => 'mg', 'iso_alpha_3' => 'mlg', 'name' => 'Malagasy', 'native' => 'fiteny malagasy'],
        ['iso_alpha_2' => 'mh', 'iso_alpha_3' => 'mah', 'name' => 'Marshallese', 'native' => 'Kajin M̧ajeļ'],
        ['iso_alpha_2' => 'mi', 'iso_alpha_3' => 'mri', 'name' => 'Maori', 'native' => 'te reo Māori'],
        ['iso_alpha_2' => 'mk', 'iso_alpha_3' => 'mkd', 'name' => 'Macedonian', 'native' => 'македонски јазик', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ml', 'iso_alpha_3' => 'mal', 'name' => 'Malayalam', 'native' => 'മലയാളം', 'script' => 'Mlym'],
        ['iso_alpha_2' => 'mn', 'iso_alpha_3' => 'mon', 'name' => 'Mongolian', 'native' => 'Монгол хэл', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'mr', 'iso_alpha_3' => 'mar', 'name' => 'Marathi', 'native' => 'मराठी', 'script' => 'Deva'],
        ['iso_alpha_2' => 'ms', 'iso_alpha_3' => 'msa', 'name' => 'Malay', 'native' => 'بهاس ملايو‎', 'script' => 'Arab'],
        ['iso_alpha_2' => 'mt', 'iso_alpha_3' => 'mlt', 'name' => 'Maltese', 'native' => 'Malti'],
        ['iso_alpha_2' => 'my', 'iso_alpha_3' => 'mya', 'name' => 'Burmese', 'native' => 'ဗမာစာ', 'script' => 'Mymr'],
        ['iso_alpha_2' => 'na', 'iso_alpha_3' => 'nau', 'name' => 'Nauru', 'native' => 'Dorerin Naoero'],
        ['iso_alpha_2' => 'nb', 'iso_alpha_3' => 'nob', 'name' => 'Bokmål', 'native' => 'Bokmål'],
        ['iso_alpha_2' => 'nd', 'iso_alpha_3' => 'nde', 'name' => 'Northern Ndebele', 'native' => 'isiNdebele (Zimbabwe)'],
        ['iso_alpha_2' => 'ne', 'iso_alpha_3' => 'nep', 'name' => 'Nepali', 'native' => 'नेपाली', 'script' => 'Deva'],
        ['iso_alpha_2' => 'ng', 'iso_alpha_3' => 'ndo', 'name' => 'Ndonga', 'native' => 'Owambo'],
        ['iso_alpha_2' => 'nl', 'iso_alpha_3' => 'nld', 'name' => 'Dutch', 'native' => 'Nederlands'],
        ['iso_alpha_2' => 'nn', 'iso_alpha_3' => 'nld', 'name' => 'Nynorsk', 'native' => 'Nynorsk'],
        ['iso_alpha_2' => 'no', 'iso_alpha_3' => 'nor', 'name' => 'Norwegian', 'native' => 'Norsk'],
        ['iso_alpha_2' => 'nr', 'iso_alpha_3' => 'nbl', 'name' => 'Southern Ndebele', 'native' => 'isiNdebele (South Africa)'],
        ['iso_alpha_2' => 'nv', 'iso_alpha_3' => 'nav', 'name' => 'Navajo', 'native' => 'Diné bizaad'],
        ['iso_alpha_2' => 'ny', 'iso_alpha_3' => 'nya', 'name' => 'Chewa', 'native' => 'chiCheŵa'],
        ['iso_alpha_2' => 'oc', 'iso_alpha_3' => 'oci', 'name' => 'Occitan', 'native' => 'occitan'],
        ['iso_alpha_2' => 'oj', 'iso_alpha_3' => 'oji', 'name' => 'Ojibwa', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'script' => 'Cans'],
        ['iso_alpha_2' => 'om', 'iso_alpha_3' => 'orm', 'name' => 'Oromo', 'native' => 'Afaan Oromoo'],
        ['iso_alpha_2' => 'or', 'iso_alpha_3' => 'ori', 'name' => 'Oriya', 'native' => 'ଓଡ଼ିଆ', 'script' => 'Orya'],
        ['iso_alpha_2' => 'os', 'iso_alpha_3' => 'oss', 'name' => 'Ossetian', 'native' => 'ирон æвзаг', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'pa', 'iso_alpha_3' => 'pan', 'name' => 'Panjabi', 'native' => 'ਪੰਜਾਬੀ', 'script' => 'Guru'],
        ['iso_alpha_2' => 'pi', 'iso_alpha_3' => 'pli', 'name' => 'Pali', 'native' => 'पाऴि', 'script' => 'Deva'],
        ['iso_alpha_2' => 'pl', 'iso_alpha_3' => 'pol', 'name' => 'Polish', 'native' => 'język polski'],
        ['iso_alpha_2' => 'ps', 'iso_alpha_3' => 'pus', 'name' => 'Pashto', 'native' => 'پښتو', 'script' => 'Arab'],
        ['iso_alpha_2' => 'pt', 'iso_alpha_3' => 'por', 'name' => 'Portuguese', 'native' => 'Português'],
        ['iso_alpha_2' => 'qu', 'iso_alpha_3' => 'que', 'name' => 'Quechua', 'native' => 'Runa Simi'],
        ['iso_alpha_2' => 'rm', 'iso_alpha_3' => 'roh', 'name' => 'Romansh', 'native' => 'Rumantsch Grischun'],
        ['iso_alpha_2' => 'rn', 'iso_alpha_3' => 'run', 'name' => 'Rundi', 'native' => 'Ikirundi'],
        ['iso_alpha_2' => 'ro', 'iso_alpha_3' => 'ron', 'name' => 'Romanian', 'native' => 'Română'],
        ['iso_alpha_2' => 'ru', 'iso_alpha_3' => 'rus', 'name' => 'Russian', 'native' => 'русский', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'rw', 'iso_alpha_3' => 'kin', 'name' => 'Kinyarwanda', 'native' => 'Ikinyarwanda'],
        ['iso_alpha_2' => 'sa', 'iso_alpha_3' => 'san', 'name' => 'Sanskrit', 'native' => 'संस्कृतम्', 'script' => 'Deva'],
        ['iso_alpha_2' => 'sc', 'iso_alpha_3' => 'srd', 'name' => 'Sardinian', 'native' => 'sardu'],
        ['iso_alpha_2' => 'sd', 'iso_alpha_3' => 'snd', 'name' => 'Sindhi', 'native' => 'سنڌي', 'script' => 'Arab'],
        ['iso_alpha_2' => 'se', 'iso_alpha_3' => 'sme', 'name' => 'Sami', 'native' => 'Davvisámegiella'],
        ['iso_alpha_2' => 'sg', 'iso_alpha_3' => 'sag', 'name' => 'Sango', 'native' => 'yângâ tî sängö'],
        ['iso_alpha_2' => 'si', 'iso_alpha_3' => 'sin', 'name' => 'Sinhala', 'native' => 'සිංහල', 'script' => 'Sinh'],
        ['iso_alpha_2' => 'sk', 'iso_alpha_3' => 'slk', 'name' => 'Slovak', 'native' => 'Slovenčina'],
        ['iso_alpha_2' => 'sl', 'iso_alpha_3' => 'slv', 'name' => 'Slovene', 'native' => 'Slovenščina'],
        ['iso_alpha_2' => 'sm', 'iso_alpha_3' => 'smo', 'name' => 'Samoan', 'native' => 'gagana fa\'a Samoa'],
        ['iso_alpha_2' => 'sn', 'iso_alpha_3' => 'sna', 'name' => 'Shona', 'native' => 'chiShona'],
        ['iso_alpha_2' => 'so', 'iso_alpha_3' => 'som', 'name' => 'Somali', 'native' => 'Soomaaliga'],
        ['iso_alpha_2' => 'sq', 'iso_alpha_3' => 'sqi', 'name' => 'Albanian', 'native' => 'Shqip'],
        ['iso_alpha_2' => 'sr', 'iso_alpha_3' => 'srp', 'name' => 'Serbian', 'native' => 'српски језик', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ss', 'iso_alpha_3' => 'ssw', 'name' => 'Swati', 'native' => 'SiSwati'],
        ['iso_alpha_2' => 'st', 'iso_alpha_3' => 'sot', 'name' => 'Sotho', 'native' => 'Sesotho'],
        ['iso_alpha_2' => 'su', 'iso_alpha_3' => 'sun', 'name' => 'Sundanese', 'native' => 'Basa Sunda'],
        ['iso_alpha_2' => 'sv', 'iso_alpha_3' => 'swe', 'name' => 'Swedish', 'native' => 'Svenska'],
        ['iso_alpha_2' => 'sw', 'iso_alpha_3' => 'swa', 'name' => 'Swahili', 'native' => 'Kiswahili'],
        ['iso_alpha_2' => 'ta', 'iso_alpha_3' => 'tam', 'name' => 'Tamil', 'native' => 'தமிழ்', 'script' => 'Taml'],
        ['iso_alpha_2' => 'te', 'iso_alpha_3' => 'tel', 'name' => 'Telugu', 'native' => 'తెలుగు', 'script' => 'Telu'],
        ['iso_alpha_2' => 'tg', 'iso_alpha_3' => 'tgk', 'name' => 'Tajik', 'native' => 'тоҷикӣ', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'th', 'iso_alpha_3' => 'tha', 'name' => 'Thai', 'native' => 'ไทย', 'script' => 'Thai'],
        ['iso_alpha_2' => 'ti', 'iso_alpha_3' => 'tir', 'name' => 'Tigrinya', 'native' => 'ትግርኛ', 'script' => 'Ethi'],
        ['iso_alpha_2' => 'tk', 'iso_alpha_3' => 'tuk', 'name' => 'Turkmen', 'native' => 'Түркмен', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'tl', 'iso_alpha_3' => 'tgl', 'name' => 'Tagalog', 'native' => 'Wikang Tagalog'],
        ['iso_alpha_2' => 'tn', 'iso_alpha_3' => 'tsn', 'name' => 'Tswana', 'native' => 'Setswana'],
        ['iso_alpha_2' => 'to', 'iso_alpha_3' => 'ton', 'name' => 'Tongan', 'native' => 'Faka Tonga'],
        ['iso_alpha_2' => 'tr', 'iso_alpha_3' => 'tur', 'name' => 'Turkish', 'native' => 'Türkçe'],
        ['iso_alpha_2' => 'ts', 'iso_alpha_3' => 'tso', 'name' => 'Tsonga', 'native' => 'Xitsonga'],
        ['iso_alpha_2' => 'tt', 'iso_alpha_3' => 'tat', 'name' => 'Tatar', 'native' => 'татар теле', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'tw', 'iso_alpha_3' => 'twi', 'name' => 'Twi', 'native' => 'Twi'],
        ['iso_alpha_2' => 'ty', 'iso_alpha_3' => 'tah', 'name' => 'Tahitian', 'native' => 'Reo Tahiti'],
        ['iso_alpha_2' => 'ug', 'iso_alpha_3' => 'uig', 'name' => 'Uighur', 'native' => 'ئۇيغۇرچە‎', 'script' => 'Arab'],
        ['iso_alpha_2' => 'uk', 'iso_alpha_3' => 'ukr', 'name' => 'Ukrainian', 'native' => 'Українська', 'script' => 'Cyrl'],
        ['iso_alpha_2' => 'ur', 'iso_alpha_3' => 'urd', 'name' => 'Urdu', 'native' => 'اردو', 'script' => 'Arab'],
        ['iso_alpha_2' => 'uz', 'iso_alpha_3' => 'uzb', 'name' => 'Uzbek', 'native' => 'O\'zbek'],
        ['iso_alpha_2' => 've', 'iso_alpha_3' => 'ven', 'name' => 'Venda', 'native' => 'Tshivenḓa'],
        ['iso_alpha_2' => 'vi', 'iso_alpha_3' => 'vie', 'name' => 'Vietnamese', 'native' => 'Tiếng Việt'],
        ['iso_alpha_2' => 'vo', 'iso_alpha_3' => 'vol', 'name' => 'Volapük', 'native' => 'Volapük'],
        ['iso_alpha_2' => 'wa', 'iso_alpha_3' => 'wln', 'name' => 'Walloon', 'native' => 'Walon'],
        ['iso_alpha_2' => 'wo', 'iso_alpha_3' => 'wol', 'name' => 'Walof', 'native' => 'Wollof'],
        ['iso_alpha_2' => 'xh', 'iso_alpha_3' => 'xho', 'name' => 'Xhosa', 'native' => 'isiXhosa'],
        ['iso_alpha_2' => 'yi', 'iso_alpha_3' => 'yid', 'name' => 'Yiddish', 'native' => 'ייִדיש', 'script' => 'Hebr'],
        ['iso_alpha_2' => 'yo', 'iso_alpha_3' => 'yor', 'name' => 'Yoruba', 'native' => 'Yorùbá'],
        ['iso_alpha_2' => 'za', 'iso_alpha_3' => 'zha', 'name' => 'Zhuang', 'native' => '話僮', 'script' => 'Hant'],
        ['iso_alpha_2' => 'zh', 'iso_alpha_3' => 'zho', 'name' => 'Chinese', 'native' => '中文', 'script' => 'Hans'],
        ['iso_alpha_2' => 'zu', 'iso_alpha_3' => 'zul', 'name' => 'Zulu', 'native' => 'isiZulu'],
    ];

    /**
     * Create a new seeder instance.
     *
     * @param Language $model
     * @return void
     */
    public function __construct(Language $model)
    {
        $this->model = $model;
    }
}
