language: php

matrix:
    fast_finish: true

php:
    - '7.2'
    - '7.3'

mysql:
    - database: ci_vertebrae

services:
    - mysql
    - memcached
    - redis-server

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - printf "\n" | pecl install -f redis
    - travis_retry composer self-update

install:
    - mysql -e 'create database ci_vertebrae;'
    - cp .env.ci .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - php artisan key:generate
    - php artisan migrate:fresh --seed
    - yarn install --pure-lockfile
    - yarn run production --progress false

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
