services:

  laravel.test:
    build:
      context: ./docker/${PHP_VERSION}
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP}
    image: sail-${PHP_VERSION}/app
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
      XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
      IGNITION_LOCAL_SITES_PATH: ${PWD}
    volumes:
      - .:/var/www/html
    networks:
      - sail
    depends_on:
      - mysql
      - pgsql
      - redis
      - typesense
      - minio
      - mailpit
      - selenium

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - ${FORWARD_DB_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE:-vertebrae}
      MYSQL_USER: ${DB_USERNAME:-sail}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_EXTRA_OPTIONS: ${MYSQL_EXTRA_OPTIONS}
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - sail
    healthcheck:
      test: [ CMD, mysqladmin, ping, '-p${DB_PASSWORD}' ]
      retries: 3
      timeout: 5s

  pgsql:
    image: postgres:17-alpine
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      PGPASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-vertebrae}
      POSTGRES_USER: ${DB_USERNAME:-sail}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - pgsql:/var/lib/postgresql/data
      - ./docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    networks:
      - sail
    healthcheck:
      test: [ CMD, pg_isready, -q, -d, '${DB_DATABASE}', -U, '${DB_USERNAME}' ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    volumes:
      - redis:/data
    networks:
      - sail
    command: redis-server --requirepass '${REDIS_PASSWORD:-null}'
    healthcheck:
      test: [ CMD, redis-cli, ping ]
      retries: 3
      timeout: 5s

  typesense:
    image: typesense/typesense:27.1
    ports:
      - ${FORWARD_TYPESENSE_PORT:-8108}:8108
    environment:
      TYPESENSE_DATA_DIR: ${TYPESENSE_DATA_DIR:-/typesense-data}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-xyz}
      TYPESENSE_ENABLE_CORS: ${TYPESENSE_ENABLE_CORS:-true}
    volumes:
      - typesense:/typesense-data
    networks:
      - sail
    healthcheck:
      test: [ CMD, bash, -c, 'exec 3<>/dev/tcp/localhost/8108 && printf ''GET /health HTTP/1.1\r\nConnection: close\r\n\r\n'' >&3 && head -n1 <&3 | grep ''200'' && exec 3>&-' ]
      retries: 5
      timeout: 7s

  minio:
    image: minio/minio:latest
    ports:
      - ${FORWARD_MINIO_PORT:-9000}:9000
      - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-sail}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-password}
    volumes:
      - minio:/data
    networks:
      - sail
    command: minio server /data --console-address ":8900"
    healthcheck:
      test: [ CMD, mc, ready, local ]
      retries: 3
      timeout: 5s

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    volumes:
      - mailpit:/data
    networks:
      - sail

  selenium:
    image: selenium/standalone-chromium
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - sail

  adminer:
    image: adminer
    ports:
      - '${ADMINER_PORT:-8081}:8080'
    networks:
      - sail
    depends_on:
      - mysql
      - pgsql

networks:
  sail:
    driver: bridge

volumes:
  mysql:
    driver: local
  pgsql:
    driver: local
  redis:
    driver: local
  typesense:
    driver: local
  minio:
    driver: local
  mailpit:
    driver: local
